hl.on("hyprland.start", function()
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("swaync")
	hl.exec_cmd("swaync")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("hyprsunset")
	hl.exec_cmd("/usr/bin/kwalletd6 & /usr/bin/kdeconnectd & kdeconnect-indicator")
	hl.exec_cmd("waybar & clipboard-sync")
	hl.exec_cmd("megasync")
	hl.exec_cmd("nextcloud --background")
	hl.exec_cmd("copyq --start-server")
	hl.exec_cmd("openrgb --startminimized")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("hyprctl setcursor shiro 24")
	hl.exec_cmd("fcitx5")
end)
