## CAVA configuration for Waybar's raw frontend.

[general]
framerate = 120
autosens = 0
sensitivity = 100
bars = 16
lower_cutoff_freq = 50
higher_cutoff_freq = 10000

[input]
method = pulse
source = auto

[output]
method = raw
channels = mono
mono_option = average
raw_target = /dev/stdout
data_format = ascii
bar_delimiter = 0

[smoothing]
waves = 1
noise_reduction = 47
